### ISSUE TITLE
compatible with LB 4.+?

### ISSUE THREAD

**Issue by materemias** [oridool/liquibase-locking#1]
Hi,

I use this with LB 3.x but could not get the extension picked up by LB  with 4.+. I am aware that with 4.0.1beta they replaced old custom classpath scanner with java.util.ServiceLoader for finding extensions, but since then the extension is not found. I tried to compile it against LB 4.3.1... still no success

**Comment by oridool** [comment]
Hi @materemias ,
Indeed the extension didn't work for LB 4.+.
I followed the upgrade recommendation from this link: 
https://docs.liquibase.com/tools-integrations/extensions/extension-upgrade-guides/lb-4.0-upgrade-guide.html
and now it appears to work correctly with LB 4.3.1.
Please review the changes in PR #2 and see if it is working for you.
